authapp/urls.py
from authapp.apps import AuthappConfig
from django.urls import path
from authapp.views import CustomLoginView, RegisterView, CustomLogoutView, EditView

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit/', EditView.as_view(), name='edit'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp.apps import MainappConfig
from mainapp import views


app_name = MainappConfig.name

urlpatterns = [
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('courses/', views.CoursesListView.as_view(), name='courses'),
    path('courses/<int:pk>/detail', views.CoursesDetailView.as_view(), name='courses_detail'),
    path('docsite/', views.DocSiteView.as_view(), name='docsite'),
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('news/', views.NewsView.as_view(), name='news'),
    path('news/<int:pk>/detail', views.NewsPageDetailView.as_view(), name='news_detail'),
]

mainapp/models.py
from email.policy import default
from enum import auto

from django.db import models


NULLABLE = {'blank': True, 'null': True}


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    deleted = models.BooleanField(default=False, verbose_name='Удален')

    class Meta:
        abstract = True
        ordering = ('-created_at',)


class NewsManager(models.Manager):
    def delete(self):
        pass

    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class News(BaseModel):
    objects = NewsManager()

    title = models.CharField(max_length=255, verbose_name='Заголовок')
    preamble = models.CharField(max_length=1000, verbose_name='Вступление')
    body = models.TextField(verbose_name='Содержимое')
    body_as_markdown = models.BooleanField(default=False, verbose_name='Способ разметки')

    def __str__(self) -> str:
        return f'#{self.pk} {self.title}'

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'


class CoursesManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class Course(BaseModel):
    objects = CoursesManager()

    name = models.CharField(max_length=256, verbose_name='Name')
    description = models.TextField(verbose_name='Description', **NULLABLE)
    description_as_markdown = models.BooleanField(verbose_name='As markdown', default=False)
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Cost', default=0)
    cover = models.CharField(max_length=25, default='no_image.svg', verbose_name='Cover')

    def __str__(self) -> str:
        return f'{self.pk} {self.name}'

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = 'курсы'


class Lesson(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name='Lesson number')
    title = models.CharField(max_length=256, verbose_name='Name')
    description = models.TextField(verbose_name='Description', **NULLABLE)
    description_as_markdown = models.BooleanField(verbose_name='As markdown', default=False)

    def __str__(self) -> str:
        return f'{self.course.name} | {self.num} | {self.title}'

    class Meta:
        verbose_name = 'урок'
        verbose_name_plural = 'уроки'
        ordering = ('course', 'num')


class CourseTeachers(models.Model):
    course = models.ManyToManyField(Course)
    name_first = models.CharField(max_length=128, verbose_name='Name')
    name_second = models.CharField(max_length=128, verbose_name='Surname')
    day_birth = models.DateField(verbose_name='Birth date')
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return '{0:0>3} {1} {2}'.format(self.pk, self.name_second, self.name_first)

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = 'учитель'
        verbose_name_plural = 'учителя'

mainapp/views.py
import json

from django.conf import settings
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404

from mainapp.models import News
from mainapp import models as mainapp_models


class ContactsView(TemplateView):
    template_name = 'mainapp/contacts.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['contacts'] = [
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHcrhA',
                'city': 'Санкт‑Петербург',
                'phone': '+7-999-11-11111',
                'email': 'geeklab@spb.ru',
                'address': 'территория Петропавловская крепость, 3Ж',
            },
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHX3xB',
                'city': 'Казань',
                'phone': '+7-999-22-22222',
                'email': 'geeklab@kz.ru',
                'address': 'территория Кремль, 11, Казань, Республика Татарстан, Россия',
            },
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHh9kD',
                'city': 'Москва',
                'phone': '+7-999-33-33333',
                'email': 'geeklab@msk.ru',
                'address': 'Красная площадь, 7, Москва, Россия',
            },
        ]

        return context_data


class CoursesListView(TemplateView):
    template_name = 'mainapp/courses_list.html'

    def get_context_data(self, **kwargs):
        context = super(CoursesListView, self).get_context_data(**kwargs)
        context['courses_list'] = mainapp_models.Course.objects.all()

        return context


class CoursesDetailView(TemplateView):
    template_name = 'mainapp/courses_detail.html'

    def get_context_data(self, pk=None, **kwargs):
        context = super(CoursesDetailView, self).get_context_data(**kwargs)
        context['course_object'] = get_object_or_404(mainapp_models.Course, pk=pk)
        context['lessons'] = mainapp_models.Lesson.objects.filter(course=context['course_object'])
        context['teachers'] = mainapp_models.CourseTeachers.objects.filter(course=context['course_object'])

        return context


class DocSiteView(TemplateView):
    template_name = 'mainapp/doc_site.html'


class IndexView(TemplateView):
    template_name = 'mainapp/index.html'


class LoginView(TemplateView):
    template_name = 'mainapp/login.html'


class NewsView(TemplateView):
    template_name = 'mainapp/news.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['news_list'] = News.objects.all()

        return context_data


class NewsPageDetailView(TemplateView):
    template_name = 'mainapp/news_detail.html'

    def get_context_data(self, pk=None, **kwargs):
        context = super().get_context_data(pk=pk, **kwargs)
        context["news_object"] = get_object_or_404(mainapp_models.News, pk=pk)

        return context

mainapp/templates/mainapp/includes/inc_main_menu.html
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
            <a class="nav-link {% if '/news/' in request.path %}active{% endif %}" href="{% url 'mainapp:news' %}">Новости</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link {% if '/courses/' in request.path %}active{% endif %}"
               href="{% url 'mainapp:courses' %}">Курсы</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                Профиль
            </a>
            <div class="dropdown-menu" aria-labelledby="ddProfile">
                <a class="dropdown-item" href="#">Редактировать профиль</a>
                <a class="dropdown-item" href="#">Мои курсы</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Модерация</a>
                <a class="dropdown-item" href="#">Административный раздел</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Выход</a>
            </div>
        </li>
        <li class="nav-item ">
            <a class="nav-link {% if '/contacts/' in request.path %}active{% endif %}"
               href="{% url 'mainapp:contacts' %}">Контакты</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item ">
                <a class="nav-link {% if '/contacts/' in request.path %}active{% endif %}"
                   href="{% url 'authapp:edit' %}">{{ user.first_name|default:user.username }}</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link {% if '/contacts/' in request.path %}active{% endif %}"
                   href="{% url 'authapp:logout' %}">Выход</a>
            </li>
        {% else %}
            <li class="nav-item ">
                <a class="nav-link {% if '/contacts/' in request.path %}active{% endif %}"
                   href="{% url 'authapp:login' %}">Вход</a>
            </li>
        {% endif %}
    </ul>
    <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>
</div>